# Site
name: Kagyu Dzamling Kunkyab São Paulo - Centro Budista Tibetano
description: Kagyu Dzamling Kunkyab São Paulo - Centro Budista Tibetano
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl:
email: 'shangpa.sp@gmail.com'
google_analytics: 'UA-46278016-1'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  palden:
    name: Kagyu Dzamling Kunkyab - SP
    display_name: Kagyu Dzamling Kunkyab - SP
    gravatar: a07793f4bd88aceb2ae90d83807f611f
    email: shangpa.sp@gmail.com
    twitter: https://www.facebook.com/PaldenShangpa/

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
